# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
puts "Creating default cities"

City.create(name: "New York City", bigger_thing: "New York", lon: -73.997009, lat: 40.750134, country: "US")
City.create(name: "Sydney", bigger_thing: "Australia", lon: 151.179993, lat: -33.950001, country: "AU")
City.create(name: "London", bigger_thing: "United Kingdom", lon: -0.45, lat: 51.48, country: "GB")
City.create(name: "Hong Kong International", bigger_thing: "China", lon: 113.914719, lat: 22.308889, country: "CN")
City.create(name: "Paris", bigger_thing: "France", lon: 2.333333, lat: 48.866665, country: "FR")

# puts "Adding cities to users"

# @user1.cities << [@Nyc, @Ldn, @Hk, @Prs, @Syd]
# @user2.cities << @Atl

# puts "Creating bonus cities"

# City.create(name: "Aberdeen")
# City.create(name: "Abilene")
# City.create(name: "Akron")
# City.create(name: "Albany")
# City.create(name: "Albuquerque")
# City.create(name: "Alexandria")
# City.create(name: "Allentown")
# City.create(name: "Amarillo")
# City.create(name: "Anaheim")
# City.create(name: "Anchorage")
# City.create(name: "Ann Arbor")
# City.create(name: "Antioch")
# City.create(name: "Apple Valley")
# City.create(name: "Appleton")
# City.create(name: "Arlington")
# City.create(name: "Arvada")
# City.create(name: "Asheville")
# City.create(name: "Athens")
# City.create(name: "Atlanta")
# City.create(name: "Atlantic City")
# City.create(name: "Augusta")
# City.create(name: "Aurora")
# City.create(name: "Austin")
# City.create(name: "Bakersfield")
# City.create(name: "Baltimore")
# City.create(name: "Barnstable")
# City.create(name: "Baton Rouge")
# City.create(name: "Beaumont")
# City.create(name: "Bel Air")
# City.create(name: "Bellevue")
# City.create(name: "Berkeley")
# City.create(name: "Bethlehem")
# City.create(name: "Billings")
# City.create(name: "Birmingham")
# City.create(name: "Bloomington")
# City.create(name: "Boise")
# City.create(name: "Boise City")
# City.create(name: "Bonita Springs")
# City.create(name: "Boston")
# City.create(name: "Boulder")
# City.create(name: "Bradenton")
# City.create(name: "Bremerton")
# City.create(name: "Bridgeport")
# City.create(name: "Brighton")
# City.create(name: "Brownsville")
# City.create(name: "Bryan")
# City.create(name: "Buffalo")
# City.create(name: "Burbank")
# City.create(name: "Burlington")
# City.create(name: "Cambridge")
# City.create(name: "Canton")
# City.create(name: "Cape Coral")
# City.create(name: "Carrollton")
# City.create(name: "Cary")
# City.create(name: "Cathedral City")
# City.create(name: "Cedar Rapids")
# City.create(name: "Champaign")
# City.create(name: "Chandler")
# City.create(name: "Charleston")
# City.create(name: "Charlotte")
# City.create(name: "Chattanooga")
# City.create(name: "Chesapeake")
# City.create(name: "Chicago")
# City.create(name: "Chula Vista")
# City.create(name: "Cincinnati")
# City.create(name: "Clarke County")
# City.create(name: "Clarksville")
# City.create(name: "Clearwater")
# City.create(name: "Cleveland")
# City.create(name: "College Station")
# City.create(name: "Colorado Springs")
# City.create(name: "Columbia")
# City.create(name: "Columbus")
# City.create(name: "Concord")
# City.create(name: "Coral Springs")
# City.create(name: "Corona")
# City.create(name: "Corpus Christi")
# City.create(name: "Costa Mesa")
# City.create(name: "Dallas")
# City.create(name: "Daly City")
# City.create(name: "Danbury")
# City.create(name: "Davenport")
# City.create(name: "Davidson County")
# City.create(name: "Dayton")
# City.create(name: "Daytona Beach")
# City.create(name: "Deltona")
# City.create(name: "Denton")
# City.create(name: "Denver")
# City.create(name: "Des Moines")
# City.create(name: "Detroit")
# City.create(name: "Downey")
# City.create(name: "Duluth")
# City.create(name: "Durham")
# City.create(name: "El Monte")
# City.create(name: "El Paso")
# City.create(name: "Elizabeth")
# City.create(name: "Elk Grove")
# City.create(name: "Elkhart")
# City.create(name: "Erie")
# City.create(name: "Escondido")
# City.create(name: "Eugene")
# City.create(name: "Evansville")
# City.create(name: "Fairfield")
# City.create(name: "Fargo")
# City.create(name: "Fayetteville")
# City.create(name: "Fitchburg")
# City.create(name: "Flint")
# City.create(name: "Fontana")
# City.create(name: "Fort Collins")
# City.create(name: "Fort Lauderdale")
# City.create(name: "Fort Smith")
# City.create(name: "Fort Walton Beach")
# City.create(name: "Fort Wayne")
# City.create(name: "Fort Worth")
# City.create(name: "Frederick")
# City.create(name: "Fremont")
# City.create(name: "Fresno")
# City.create(name: "Fullerton")
# City.create(name: "Gainesville")
# City.create(name: "Garden Grove")
# City.create(name: "Garland")
# City.create(name: "Gastonia")
# City.create(name: "Gilbert")
# City.create(name: "Glendale")
# City.create(name: "Grand Prairie")
# City.create(name: "Grand Rapids")
# City.create(name: "Grayslake")
# City.create(name: "Green Bay")
# City.create(name: "GreenBay")
# City.create(name: "Greensboro")
# City.create(name: "Greenville")
# City.create(name: "Gulfport-Biloxi")
# City.create(name: "Hagerstown")
# City.create(name: "Hampton")
# City.create(name: "Harlingen")
# City.create(name: "Harrisburg")
# City.create(name: "Hartford")
# City.create(name: "Havre de Grace")
# City.create(name: "Hayward")
# City.create(name: "Hemet")
# City.create(name: "Henderson")
# City.create(name: "Hesperia")
# City.create(name: "Hialeah")
# City.create(name: "Hickory")
# City.create(name: "High Point")
# City.create(name: "Hollywood")
# City.create(name: "Honolulu")
# City.create(name: "Houma")
# City.create(name: "Houston")
# City.create(name: "Howell")
# City.create(name: "Huntington")
# City.create(name: "Huntington Beach")
# City.create(name: "Huntsville")
# City.create(name: "Independence")
# City.create(name: "Indianapolis")
# City.create(name: "Inglewood")
# City.create(name: "Irvine")
# City.create(name: "Irving")
# City.create(name: "Jackson")
# City.create(name: "Jacksonville")
# City.create(name: "Jefferson")
# City.create(name: "Jersey City")
# City.create(name: "Johnson City")
# City.create(name: "Joliet")
# City.create(name: "Kailua")
# City.create(name: "Kalamazoo")
# City.create(name: "Kaneohe")
# City.create(name: "Kansas City")
# City.create(name: "Kennewick")
# City.create(name: "Kenosha")
# City.create(name: "Killeen")
# City.create(name: "Kissimmee")
# City.create(name: "Knoxville")
# City.create(name: "Lacey")
# City.create(name: "Lafayette")
# City.create(name: "Lake Charles")
# City.create(name: "Lakeland")
# City.create(name: "Lakewood")
# City.create(name: "Lancaster")
# City.create(name: "Lansing")
# City.create(name: "Laredo")
# City.create(name: "Las Cruces")
# City.create(name: "Las Vegas")
# City.create(name: "Layton")
# City.create(name: "Leominster")
# City.create(name: "Lewisville")
# City.create(name: "Lexington")
# City.create(name: "Lincoln")
# City.create(name: "Little Rock")
# City.create(name: "Long Beach")
# City.create(name: "Lorain")
# City.create(name: "Los Angeles")
# City.create(name: "Louisville")
# City.create(name: "Lowell")
# City.create(name: "Lubbock")
# City.create(name: "Macon")
# City.create(name: "Madison")
# City.create(name: "Manchester")
# City.create(name: "Marina")
# City.create(name: "Marysville")
# City.create(name: "McAllen")
# City.create(name: "McHenry")
# City.create(name: "Medford")
# City.create(name: "Melbourne")
# City.create(name: "Memphis")
# City.create(name: "Merced")
# City.create(name: "Mesa")
# City.create(name: "Mesquite")
# City.create(name: "Miami")
# City.create(name: "Milwaukee")
# City.create(name: "Minneapolis")
# City.create(name: "Miramar")
# City.create(name: "Mission Viejo")
# City.create(name: "Mobile")
# City.create(name: "Modesto")
# City.create(name: "Monroe")
# City.create(name: "Monterey")
# City.create(name: "Montgomery")
# City.create(name: "Moreno Valley")
# City.create(name: "Murfreesboro")
# City.create(name: "Murrieta")
# City.create(name: "Muskegon")
# City.create(name: "Myrtle Beach")
# City.create(name: "Naperville")
# City.create(name: "Naples")
# City.create(name: "Nashua")
# City.create(name: "Nashville")
# City.create(name: "New Bedford")
# City.create(name: "New Haven")
# City.create(name: "New London")
# City.create(name: "New Orleans")
# City.create(name: "New York")
# City.create(name: "New York City")
# City.create(name: "Newark")
# City.create(name: "Newburgh")
# City.create(name: "Newport News")
# City.create(name: "Norfolk")
# City.create(name: "Normal")
# City.create(name: "Norman")
# City.create(name: "North Charleston")
# City.create(name: "North Las Vegas")
# City.create(name: "North Port")
# City.create(name: "Norwalk")
# City.create(name: "Norwich")
# City.create(name: "Oakland")
# City.create(name: "Ocala")
# City.create(name: "Oceanside")
# City.create(name: "Odessa")
# City.create(name: "Ogden")
# City.create(name: "Oklahoma City")
# City.create(name: "Olathe")
# City.create(name: "Olympia")
# City.create(name: "Omaha")
# City.create(name: "Ontario")
# City.create(name: "Orange")
# City.create(name: "Orem")
# City.create(name: "Orlando")
# City.create(name: "Overland Park")
# City.create(name: "Oxnard")
# City.create(name: "Palm Bay")
# City.create(name: "Palm Springs")
# City.create(name: "Palmdale")
# City.create(name: "Panama City")
# City.create(name: "Pasadena")
# City.create(name: "Paterson")
# City.create(name: "Pembroke Pines")
# City.create(name: "Pensacola")
# City.create(name: "Peoria")
# City.create(name: "Philadelphia")
# City.create(name: "Phoenix")
# City.create(name: "Pittsburgh")
# City.create(name: "Plano")
# City.create(name: "Pomona")
# City.create(name: "Pompano Beach")
# City.create(name: "Port Arthur")
# City.create(name: "Port Orange")
# City.create(name: "Port Saint Lucie")
# City.create(name: "Port St. Lucie")
# City.create(name: "Portland")
# City.create(name: "Portsmouth")
# City.create(name: "Poughkeepsie")
# City.create(name: "Providence")
# City.create(name: "Provo")
# City.create(name: "Pueblo")
# City.create(name: "Punta Gorda")
# City.create(name: "Racine")
# City.create(name: "Raleigh")
# City.create(name: "Rancho Cucamonga")
# City.create(name: "Reading")
# City.create(name: "Redding")
# City.create(name: "Reno")
# City.create(name: "Richland")
# City.create(name: "Richmond")
# City.create(name: "Richmond County")
# City.create(name: "Riverside")
# City.create(name: "Roanoke")
# City.create(name: "Rochester")
# City.create(name: "Rockford")
# City.create(name: "Roseville")
# City.create(name: "Round Lake Beach")
# City.create(name: "Sacramento")
# City.create(name: "Saginaw")
# City.create(name: "Saint Louis")
# City.create(name: "Saint Paul")
# City.create(name: "Saint Petersburg")
# City.create(name: "Salem")
# City.create(name: "Salinas")
# City.create(name: "Salt Lake City")
# City.create(name: "San Antonio")
# City.create(name: "San Bernardino")
# City.create(name: "San Buenaventura")
# City.create(name: "San Diego")
# City.create(name: "San Francisco")
# City.create(name: "San Jose")
# City.create(name: "Santa Ana")
# City.create(name: "Santa Barbara")
# City.create(name: "Santa Clara")
# City.create(name: "Santa Clarita")
# City.create(name: "Santa Cruz")
# City.create(name: "Santa Maria")
# City.create(name: "Santa Rosa")
# City.create(name: "Sarasota")
# City.create(name: "Savannah")
# City.create(name: "Scottsdale")
# City.create(name: "Scranton")
# City.create(name: "Seaside")
# City.create(name: "Seattle")
# City.create(name: "Sebastian")
# City.create(name: "Shreveport")
# City.create(name: "Simi Valley")
# City.create(name: "Sioux City")
# City.create(name: "Sioux Falls")
# City.create(name: "South Bend")
# City.create(name: "South Lyon")
# City.create(name: "Spartanburg")
# City.create(name: "Spokane")
# City.create(name: "Springdale")
# City.create(name: "Springfield")
# City.create(name: "St. Louis")
# City.create(name: "St. Paul")
# City.create(name: "St. Petersburg")
# City.create(name: "Stamford")
# City.create(name: "Sterling Heights")
# City.create(name: "Stockton")
# City.create(name: "Sunnyvale")
# City.create(name: "Syracuse")
# City.create(name: "Tacoma")
# City.create(name: "Tallahassee")
# City.create(name: "Tampa")
# City.create(name: "Temecula")
# City.create(name: "Tempe")
# City.create(name: "Thornton")
# City.create(name: "Thousand Oaks")
# City.create(name: "Toledo")
# City.create(name: "Topeka")
# City.create(name: "Torrance")
# City.create(name: "Trenton")
# City.create(name: "Tucson")
# City.create(name: "Tulsa")
# City.create(name: "Tuscaloosa")
# City.create(name: "Tyler")
# City.create(name: "Utica")
# City.create(name: "Vallejo")
# City.create(name: "Vancouver")
# City.create(name: "Vero Beach")
# City.create(name: "Victorville")
# City.create(name: "Virginia Beach")
# City.create(name: "Visalia")
# City.create(name: "Waco")
# City.create(name: "Warren")
# City.create(name: "Washington")
# City.create(name: "Waterbury")
# City.create(name: "Waterloo")
# City.create(name: "West Covina")
# City.create(name: "West Valley City")
# City.create(name: "Westminster")
# City.create(name: "Wichita")
# City.create(name: "Wilmington")
# City.create(name: "Winston")
# City.create(name: "Winter Haven")
# City.create(name: "Worcester")
# City.create(name: "Yakima")
# City.create(name: "Yonkers")
# City.create(name: "York") 



# puts "Creating articles"

# @article1 = Article.create(
#      title: "Article 1 Title",
#   abstract: "article 1 abstract article 1 abstract article 1 abstract article 1 abstract article 1 abstract article 1 abstract article 1 abstract article 1 abstract ",
#        url: "http://www.storyplace.com/article1",
#     source: "http://www.storyplace.com",
#       date: "2013-08-20"
#   )

# @article2 = Article.create(
#      title: "Article 2 Title",
#   abstract: "article 2 abstract article 2 abstract article 2 abstract article 2 abstract article 2 abstract article 2 abstract article 2 abstract article 2 abstract ",
#        url: "http://www.articlesource.com/article2",
#     source: "http://www.articlesource.com",
#       date: "2010-04-10"
#   )

# @article3 = Article.create(
#      title: "Article 3 Title",
#   abstract: "article 3 abstract article 3 abstract article 3 abstract article 3 abstract article 3 abstract article 3 abstract article 3 abstract article 3 abstract ",
#        url: "http://www.newsy.com/article3",
#     source: "http://www.newsy.com",
#       date: "2007-02-08"
#   )

# @article4 = Article.create(
#      title: "Article 4 Title",
#   abstract: "article 4 abstract article 4 abstract article 4 abstract article 4 abstract article 4 abstract article 4 abstract article 4 abstract article 4 abstract ",
#        url: "http://www.bigexclusive.com/article4",
#     source: "http://www.bigexclusive.com",
#       date: "1990-05-01"
#   )

# @article5 = Article.create(
#      title: "Article 5 Title",
#   abstract: "article 5 abstract article 5 abstract article 5 abstract article 5 abstract article 5 abstract article 5 abstract article 5 abstract article 5 abstract ",
#        url: "http://www.lolstuff.com/article5",
#     source: "http://www.lolstuff.com",
#       date: "2012-01-23"
#   )

# puts "Assigning articles to users"

# @user1.articles = [@article1, @article3, @article5]
# @user2.articles = [@article2, @article3, @article4]
# @user3.articles = [@article2, @article5, @article1, @article3]

# puts "Saving users"

# @user1.save
# @user2.save
# @user3.save

puts "Seeding complete!"

